seveas/python-hpilo

firmware.conf
This adds ilo2 firmwares 2.30 and 2.31 and ilo3 1.89
Includes previous update done by @sshmanko
=> Update for new firmwares

firmware.conf
also changed https->http for 2.31, as all other links are http
=> add ilo2_232

firmware.conf
firmware.conf updated accordingly
=> New Ilo4 (2.61) & Ilo5 (1.35) support

firmware.conf
=> Add iLo5 1.37

firmware.conf
=> adding new iLO3 1.91

hpilo.py
Some old Blades are still using RC4-SHA which was dropped from the
default SSL cipher suite in both Python 2.7.10 and Python 3.4.4. This
change adds the cipher back to the default list.
=> Add RC4-SHA to SSL ciphers

hpilo.py
+ INDEX should be an attribute
+ Enforce index to be a string
=> Fix delete_sso_server function

firmware.conf
Update firmware.conf with 1.92 iLO3 version.
=> Add iLO3 version 1.92 (Mai 2020)

firmware.conf
*Critical Firmware Update*
Changelog
-----------
+ Ripple20 vulnerabilities might affect the TCP/IP stack.
=> Add support for iLO3 v1.93

hpilo.py
This will add following vars:
* remote_console_status
* ribcl_status
* virtual_media_status
* webgui_status
* webserver_status
* alertmail_smtp_auth_enable
* alertmail_smtp_auth_username
* alertmail_smtp_secure_enable
Added mapping for following vars:
* serial_cli_speed
* serial_cli_status
* authentication_failure_logging
=> Add missing vars and mapping of 3 vars in mod_global_settings

firmware.conf
* Update firmware.conf accordingly
=> Support 2.76 Ilo4 version

firmware.conf
Critical update
Reference:
https://support.hpe.com/hpesc/public/docDisplay?docLocale=en_US&docId=hpesbhf04070en_us
=> Support Ilo4 2.77 & Ilo3 1.94

firmware.conf
Update firmware.conf accordingly
=> Add ilo5 2.44 version

firmware.conf
Sorry,
After opening my eyes, I noticed the url was 2.77 alike.
Fixed with the right url.
=> Add ilo4 v2.78 v2

firmware.conf
Add the following iLO5 version:
* 2.44
* 2.46
* 2.55
* 2.60
=> Add support for latest iLO5 firmware

firmware.conf
Update firmware.conf accordingly
=> Update iLO5 to v2.63

firmware.conf
=> Add support for iLO4 2.81

firmware.conf
=> Support iLO5 up to 2.72

firmware.conf
Add support for 2.78 iLO5 version
=> Add support for iLO5 v2.78

firmware.conf
=> Add support for iLO4 v2.82

firmware.conf
=> Add latest ilo5 versions

firmware.conf
Add revision:
* 2.97
* 2.98
* 2.99
=> Add support for Ilo5 up to 2.99
